language: java
jdk:
  - oraclejdk8
sudo: true
dist: precise
install: /bin/true
notifications:
  email:
    - github-awsforjava@amazon.com
script: mvn -q install -pl :sdk-core --am

after_success:
    - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
